// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:fitt_app/storage/hive_adapters.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(CategoriesAdapter());
    registerAdapter(GenderAdapter());
    registerAdapter(ProductAdapter());
    registerAdapter(SubscriptionTypeAdapter());
    registerAdapter(UserProfileModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(CategoriesAdapter());
    registerAdapter(GenderAdapter());
    registerAdapter(ProductAdapter());
    registerAdapter(SubscriptionTypeAdapter());
    registerAdapter(UserProfileModelAdapter());
  }
}
